name: statistics-resampling-online
channels:
  - conda-forge
dependencies:
  - pip
  # GNU Octave for JupyterLab
  - octave
  - octave_kernel
  # For compiling Octave packages
  - compilers
  - make
  # Runtime dependencies for some Octave package
  - gnutls
  - sympy
  # Spreadsheet editor for JupyterLab
  - jupyterlab-spreadsheet-editor
  # R
  - r-base
  - r-tidyverse
