name: statistics-resampling-online
channels:
  - conda-forge
dependencies:
  - nbgitpuller
  # GNU Octave for JupyterLab
  - octave
  - octave_kernel
  # For compiling packages
  - compilers
  - make
  # R (including package manager)
  - r-base=4.1.2-1
  # Jupyter Lab extensions
  - jupyterlab-spreadsheet-editor
  - jupyterlab-drawio
  - jupyterlab-latex
  
