name: statistics-resampling-online
channels:
  - conda-forge
dependencies:
  - python = 3.10.12
  - nbgitpuller
  # GNU Octave for JupyterLab
  # Octave 8.3 is the latest version to work with the same dependencies as R 4.1.3
  - octave = 8.3 
  - octave_kernel
  # For compiling packages
  - compilers
  - make
  # R (including package manager)
  # R 4.1.3 is the latest version to use R_GE_version == 14, which is compatible with RStudio server 2022.12.0+353 on binder
  - r-essentials = 4.1
  - r-markdown
  # Jupyter Lab extensions
  - jupyterlab-spreadsheet-editor
  - jupyterlab-drawio
  - jupyterlab-latex
  
