name: statistics-resampling-online
channels:
  - conda-forge
dependencies:
  - nbgitpuller
  # GNU Octave for JupyterLab
  - octave = 8.4
  - octave_kernel
  # For compiling packages
  - compilers
  - make
  # R (including package manager)
  - r-essentials = 4.1.3
  # Jupyter Lab extensions
  - jupyterlab-spreadsheet-editor
  - jupyterlab-drawio
  - jupyterlab-latex
  
