name: statistics-resampling-online
channels:
  - conda-forge
dependencies:
  - nbgitpuller
  # GNU Octave for JupyterLab
  - octave
  - octave_kernel
  # For compiling packages
  - compilers
  - make
  # R (including package manager)
  - r-base
  # Jupyter Lab extensions
  - jupyterlab-spreadsheet-editor
  - jupyterlab-drawio
  - jupyterlab-latex
  - jupyterlab-git
  - jupyterlab-github
  - jupyterlab-filesystem-access
  - jupyterlab-system-monitor
  - jupyterlab-search-replace
  - jupyterlab-link-share
  - jupyterlab-email
