name: repo2docker - Build and push docker image

on: 
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "dev" ]

jobs:
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
    - name: cache binder build on mybinder.org
      uses: acpennlab/statistics-resampling-online@dev
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org 
                                                 # with the branch that was pushed on.

  binder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: update jupyter dependencies with repo2docker
      uses: acpennlab/statistics-resampling-online@dev
      with:
        DOCKER_USERNAME: ${{ secrets.acpennlab }}
        DOCKER_PASSWORD: ${{ secrets.dckr_pat_mkj9kmLPVVq_BG3unSuavMzsX7E }}
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
